api:
  dashboard: true
  insecure: true  # Sadece test ortamı için

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

log:
  level: DEBUG  # Hata ayıklama için