api:
  dashboard: true
  insecure: true  # Yalnızca yerel geliştirme için açık

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"  # Şu anda kullanılmıyor ama gelecekte HTTPS için hazır

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

log:
  level: DEBUG  # Geliştirme sırasında hata ayıklama için faydalı

accessLog: {}  # İsteğe bağlı, tüm erişim kayıtlarını loglar

# metrics:
#   prometheus: {}  # Eğer Prometheus ile monitoring yapılmıyorsa kapatılabilir

# pilot:
#   dashboard: false  # Traefik Pilot kullanılmıyorsa gerek yok
